require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

async function verify() {
  console.log('--- Neutral DB Seed Verification ---');
  
  const tables = [
    'categories', 'products', 'customers', 'orders', 'order_items', 
    'reviews', 'nav_items', 'shipping_zones', 'coupons', 'site_settings',
    'contact_messages', 'SizeGuide'
  ];

  for (const table of tables) {
    const { count, error } = await supabase.from(table).select('*', { count: 'exact', head: true });
    if (error) {
      console.error(`[${table}] ERROR:`, error.message);
    } else {
      console.log(`[${table}] Count: ${count}`);
    }
  }

  console.log('\n--- Relational Integrity Check ---');
  
  // Check Orders -> Customers
  const { data: orders } = await supabase.from('orders').select('id, customer_id');
  if (orders && orders.length > 0) {
    const { data: customers } = await supabase.from('customers').select('id');
    const customerIds = customers.map(c => c.id);
    const brokenOrders = orders.filter(o => !customerIds.includes(o.customer_id));
    if (brokenOrders.length > 0) {
      console.log(`❌ ERROR: Found ${brokenOrders.length} orders pointing to missing customers.`);
    } else {
      console.log(`✅ Orders -> Customers integrity verified.`);
    }
  }

  // Check OrderItems -> Orders & Products
  const { data: orderItems } = await supabase.from('order_items').select('id, order_id, product_id');
  if (orderItems && orderItems.length > 0) {
    const { data: products } = await supabase.from('products').select('id');
    const productIds = products.map(p => p.id);
    const orderIds = orders.map(o => o.id);
    
    const brokenOrd = orderItems.filter(oi => !orderIds.includes(oi.order_id));
    const brokenProd = orderItems.filter(oi => !productIds.includes(oi.product_id));
    
    if (brokenOrd.length > 0 || brokenProd.length > 0) {
      console.log(`❌ ERROR: Broken order_items relations.`);
    } else {
      console.log(`✅ OrderItems -> Orders & Products integrity verified.`);
    }
  }

  // Check Reviews -> Products
  const { data: reviews } = await supabase.from('reviews').select('id, product_id');
  if (reviews && reviews.length > 0) {
    const { data: products } = await supabase.from('products').select('id');
    const productIds = products.map(p => p.id);
    const brokenRev = reviews.filter(r => !productIds.includes(r.product_id));
    if (brokenRev.length > 0) {
      console.log(`❌ ERROR: Found ${brokenRev.length} reviews pointing to missing products.`);
    } else {
      console.log(`✅ Reviews -> Products integrity verified.`);
    }
  }

  console.log('--- Coverage Check ---');
  // We missed seeding custom_requests, contact_messages, and SizeGuide.
  // Is this okay? Typically these are generated by user actions, not admin config.
  console.log('Note: contact_messages, custom_requests, and SizeGuide were intentionally left un-seeded as they are dynamic user-generated entities or non-core config.');
}

verify();
